import { Plan } from "./types/plans";
import { AvailablePlans } from "./types/plans";

export const plans: Record<AvailablePlans, Plan> = {
  Plus: {
    id: "1",
    name: "Plus",
    price: 9.99,
    order: 1,
    isPopular: false,
    features: [
      {
        id: "1",
        key: 'credits',
        title: "Generate 1200 songs /year",
        paneTitle: "Get 5K credits /month",
        paneTitleIcon: null,
        description: "That equals to 100 full songs or instrumentals, and 40 sound effects generations.",
        order: 1,
      },
      {
        id: "2",
        key: 'downloads',
        title: "Unlimited downloads",
        paneTitle: "∞ Unlimited downloads",
        paneTitleIcon: null,
        description: "Download your own creations, and anything from our library in best quality at no cost.",
        order: 2,
      },
      {
        id: "3",
        key: 'features',
        title: "Standard tool",
        paneTitle: "Core features",
        paneTitleIcon: null,
        description: null,
        descriptionList: [
            {
                id: "1",
                icon: 'music',
                title: 'Songs',
                description: 'Create full songs and add your own lyrics.',
                order: 1,
            },
            {
                id: "2",
                icon: 'guitar',
                title: 'Instrumentals',
                description: 'Generate instrumental songs without vocals',
                order: 2,
            },
            {
                id: "3",
                icon: 'audio-waveform',
                title: 'Sound effects',
                description: 'Create sound effects and samples.',
                order: 3,
            }
        ],
        order: 3,
      },
      {
        id: "4",
        key: 'fastgen',
        title: "Fastlane queue",
        paneTitle: "Fastlane queue",
        paneTitleIcon: "zap",
        description: "Get prioritized in the queue and enjoy lower waiting times.",
        order: 4,
      },
      {
        id: "5",
        key: 'commercial',
        title: "Commercial use",
        paneTitle: "Commercial use",
        paneTitleIcon: null,
        description: "Use your downloads anywhere.",
        order: 5,
      },
    ],
  },
  Pro: {
    id: "2",
    name: "Pro",
    price: 16.99,
    order: 2,
    isPopular: true,
    features: [
      {
        id: "1",
        key: 'credits',
        title: "Generate 6000 songs /year",
        paneTitle: "Get 25K credits /month",
        paneTitleIcon: null,
        description: "That equals to 500 full songs or instrumentals, and 200 sound effects generations.",
        order: 1,
      },
      {
        id: "2",
        key: 'downloads',
        title: "Unlimited downloads",
        paneTitle: "∞ Unlimited downloads",
        paneTitleIcon: null,
        description: "Download your own creations, and anything from our library in best quality at no cost.",
        order: 2,
      },
      {
        id: "3",
        key: 'features',
        title: "Unlock all features",
        paneTitle: "Unlock all features",
        paneTitleIcon: "lock-open",
        description: null,
        descriptionList: [
            {
                id: "1",
                icon: 'music',
                title: 'Song generation',
                description: 'Create songs, instrumentals, sound effects',
                order: 1,
            },
            {
                id: "2",
                icon: 'type',
                title: 'Text to Speech',
                description: 'Speak text in any voice',
                order: 2,
            },
            {
                id: "3",
                icon: 'blend',
                title: 'Remix',
                description: 'Remix a song with custom style or lyrics',
                order: 3,
            },
            {
                id: "4",
                icon: 'replace',
                title: 'Replace',
                description: 'Replace a part of a song with something new',
                order: 4,
            },
            {
                id: "5",
                icon: 'log-out',
                title: 'Extend',
                description: 'Continue a track beyond the original',
                order: 5,
            },
            {
                id: "6",
                icon: 'rows-2',
                title: 'Stem download',
                description: 'Dowload instrumental and vocals individually',
                order: 6,
            }
        ],
        order: 3,
      },
      {
        id: "4",
        key: 'fastgen',
        title: "Fast generation",
        paneTitle: "Fast generation",
        paneTitleIcon: "zap",
        description: "Skip the queue and get exclusive access our premium server infrastructure for faster generations.",
        order: 4,
      },
      {
        id: "5",
        key: 'commercial',
        title: "Commercial use",
        paneTitle: "Commercial use",
        paneTitleIcon: null,
        description: "Use your downloads anywhere.",
        order: 5,
      },
    ],
  },
  Ultra: {
    id: "3",
    name: "Ultra",
    price: 32.99,
    order: 3,
    isPopular: false,
    features: [
      {
        id: "1",
        key: 'credits',
        title: "Unlimited generations",
        paneTitle: "∞ Unlimited credits",
        paneTitleIcon: null,
        description: "That equals to unlimited full songs or instrumentals, and unlimited sound effects generations.",
        order: 1,
      },
      {
        id: "2",
        key: 'downloads',
        title: "Unlimited downloads",
        paneTitle: "∞ Unlimited downloads",
        paneTitleIcon: null,
        description: "Download your own creations, and anything from our library in best quality at no cost.",
        order: 2,
      },
      {
        id: "3",
        key: 'features',
        title: "Unlock all features",
        paneTitle: "Unlock all features",
        paneTitleIcon: "lock-open",
        description: null,
        descriptionList: [
            {
                id: "1",
                icon: 'music',
                title: 'Song generation',
                description: 'Create songs, instrumentals, sound effects',
                order: 1,
            },
            {
                id: "2",
                icon: 'type',
                title: 'Text to Speech',
                description: 'Speak text in any voice',
                order: 2,
            },
            {
                id: "3",
                icon: 'blend',
                title: 'Remix',
                description: 'Remix a song with custom style or lyrics',
                order: 3,
            },
            {
                id: "4",
                icon: 'replace',
                title: 'Replace',
                description: 'Replace a part of a song with something new',
                order: 4,
            },
            {
                id: "5",
                icon: 'log-out',
                title: 'Extend',
                description: 'Continue a track beyond the original',
                order: 5,
            },
            {
                id: "6",
                icon: 'rows-2',
                title: 'Stem download',
                description: 'Dowload instrumental and vocals individually',
                order: 6,
            }
        ],
        order: 3,
      },
      {
        id: "4",
        key: 'fastgen',
        title: "Fast generation",
        paneTitle: "Fast generation",
        paneTitleIcon: "zap",
        description: "Skip the queue and get exclusive access our premium server infrastructure for faster generations.",
        order: 4,
      },
      {
        id: "5",
        key: 'commercial',
        title: "Commercial use",
        paneTitle: "Commercial use",
        paneTitleIcon: null,
        description: "Use your downloads anywhere.",
        order: 5,
      },
    ],
  },
};
